//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string FACEBOOK { get; set; }
        public int? ID_AUTO { get; set; }
        public int? ID_SERVICIO { get; set; }

        [System.ComponentModel.Browsable(false)]
        public virtual AUTOS AUTOS { get; set; }

        [System.ComponentModel.Browsable(false)]
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
